// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEoldFC6o9WaPJJ-ZLuErxVj_fHKrnGXI',
    appId: '1:382601789523:web:8e5598d4a5e2e4dff586a6',
    messagingSenderId: '382601789523',
    projectId: 'stocker-e0e04',
    authDomain: 'stocker-e0e04.firebaseapp.com',
    storageBucket: 'stocker-e0e04.appspot.com',
    measurementId: 'G-HXQ90C5T19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBTv1zvi9hiTAH1ycXfGMC3rMBUwo-fOc',
    appId: '1:382601789523:android:7b96f0fbe3fb1006f586a6',
    messagingSenderId: '382601789523',
    projectId: 'stocker-e0e04',
    storageBucket: 'stocker-e0e04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASmnmDy6MhKVaFK08P2m3Rm7iOUhOUw9Y',
    appId: '1:382601789523:ios:b260e6fd5c212e90f586a6',
    messagingSenderId: '382601789523',
    projectId: 'stocker-e0e04',
    storageBucket: 'stocker-e0e04.appspot.com',
    iosClientId: '382601789523-ujf0u7ip4io9inknfot0ecoacmi7vshr.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockAppWithFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASmnmDy6MhKVaFK08P2m3Rm7iOUhOUw9Y',
    appId: '1:382601789523:ios:d254f041fefa7869f586a6',
    messagingSenderId: '382601789523',
    projectId: 'stocker-e0e04',
    storageBucket: 'stocker-e0e04.appspot.com',
    iosClientId: '382601789523-bauph55at7m4a963q8psq5qcnfsqecai.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockAppWithFlutter.RunnerTests',
  );
}
